# Generated by cucumber-sinatra. (2015-10-07 15:52:50 -0500)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'sinatra_tiny_url_app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = SinatraTinyUrl

class SinatraTinyUrlWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  SinatraTinyUrlWorld.new
end
